::1 - - [14/Jun/2025 15:32:31] "HEAD / HTTP/1.1" 200 -
::1 - - [14/Jun/2025 15:32:45] "GET / HTTP/1.1" 200 -
----------------------------------------
Exception occurred during processing of request from ('::1', 59635, 0, 0)
Traceback (most recent call last):
  File "/Users/sven/.pyenv/versions/3.12.0/lib/python3.12/socketserver.py", line 692, in process_request_thread
    self.finish_request(request, client_address)
  File "/Users/sven/.pyenv/versions/3.12.0/lib/python3.12/http/server.py", line 1311, in finish_request
    self.RequestHandlerClass(request, client_address, self,
  File "/Users/sven/.pyenv/versions/3.12.0/lib/python3.12/http/server.py", line 672, in __init__
    super().__init__(*args, **kwargs)
  File "/Users/sven/.pyenv/versions/3.12.0/lib/python3.12/socketserver.py", line 761, in __init__
    self.handle()
  File "/Users/sven/.pyenv/versions/3.12.0/lib/python3.12/http/server.py", line 436, in handle
    self.handle_one_request()
  File "/Users/sven/.pyenv/versions/3.12.0/lib/python3.12/http/server.py", line 424, in handle_one_request
    method()
  File "/Users/sven/.pyenv/versions/3.12.0/lib/python3.12/http/server.py", line 679, in do_GET
    self.copyfile(f, self.wfile)
  File "/Users/sven/.pyenv/versions/3.12.0/lib/python3.12/http/server.py", line 878, in copyfile
    shutil.copyfileobj(source, outputfile)
  File "/Users/sven/.pyenv/versions/3.12.0/lib/python3.12/shutil.py", line 204, in copyfileobj
    fdst_write(buf)
  File "/Users/sven/.pyenv/versions/3.12.0/lib/python3.12/socketserver.py", line 840, in write
    self._sock.sendall(b)
BrokenPipeError: [Errno 32] Broken pipe
----------------------------------------
::1 - - [14/Jun/2025 15:32:47] "GET / HTTP/1.1" 200 -
::1 - - [14/Jun/2025 15:32:47] code 404, message File not found
::1 - - [14/Jun/2025 15:32:47] "GET /favicon.ico HTTP/1.1" 404 -
::1 - - [14/Jun/2025 15:32:49] "GET / HTTP/1.1" 304 -
